server:
  port: 8080

spring:
  application:
    name: dl-lab
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/jwt_security?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hks13579

  jpa:
    properties:
      hibernate:
        ddl-auto: create

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: test

---
spring.config.activate.on-profile: prod
